name: Scheduled security audit

on:
  schedule:
    # run everyday at midnight
    - cron: '0 0 * * *'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit

      - run: cargo audit
